import type { MainTableProps } from "../../models/mainTableModels";

function useAdminPageHook() {
  const isAdmin = true;
  const tableMainData: MainTableProps = {
    tableTitle: ["Date", "Games", "Pick", "Result", "Profit","Actions"],
    tableName: "Today's Results",
    tableMainData: [
      {
        id: "1",
        date: "2025-09-30",
        games: "A vs B",
        pick: "A",
        result: true,
        profit: "+100",
      },
      {
        id: "2",
        date: "2025-09-29",
        games: "C vs D",
        pick: "D",
        result: false,
        profit: "-50",
      },
      {
        id: "3",
        date: "2025-09-28",
        games: "E vs F",
        pick: "F",
        result: true,
        profit: "+200",
      },
      {
        id: "4",
        date: "2025-09-27",
        games: "G vs H",
        pick: "H",
        result: true,
        profit: "+150",
      },
      {
        id: "5",
        date: "2025-09-26",
        games: "I vs J",
        pick: "I",
        result: false,
        profit: "-80",
      },
      {
        id: "6",
        date: "2025-09-25",
        games: "K vs L",
        pick: "K",
        result: true,
        profit: "+120",
      },
      {
        id: "7",
        date: "2025-09-24",
        games: "M vs N",
        pick: "M",
        result: false,
        profit: "-60",
      },
      {
        id: "8",
        date: "2025-09-23",
        games: "O vs P",
        pick: "O",
        result: true,
        profit: "+90",
      },
      {
        id: "9",
        date: "2025-09-22",
        games: "Q vs R",
        pick: "R",
        result: false,
        profit: "-40",
      },
      {
        id: "10",
        date: "2025-09-21",
        games: "S vs T",
        pick: "S",
        result: true,
        profit: "+110",
      },
      {
        id: "11",
        date: "2025-09-20",
        games: "U vs V",
        pick: "U",
        result: false,
        profit: "-30",
      },
      {
        id: "12",
        date: "2025-09-19",
        games: "W vs X",
        pick: "X",
        result: true,
        profit: "+250",
      },
      {
        id: "13",
        date: "2025-09-18",
        games: "Y vs Z",
        pick: "Y",
        result: true,
        profit: "+140",
      },
      {
        id: "14",
        date: "2025-09-17",
        games: "AA vs BB",
        pick: "BB",
        result: false,
        profit: "-70",
      },
      {
        id: "15",
        date: "2025-09-16",
        games: "CC vs DD",
        pick: "CC",
        result: true,
        profit: "+95",
      },
      {
        id: "16",
        date: "2025-09-15",
        games: "EE vs FF",
        pick: "EE",
        result: false,
        profit: "-55",
      },
      {
        id: "17",
        date: "2025-09-14",
        games: "GG vs HH",
        pick: "GG",
        result: true,
        profit: "+175",
      },
      {
        id: "18",
        date: "2025-09-13",
        games: "II vs JJ",
        pick: "JJ",
        result: false,
        profit: "-65",
      },
      {
        id: "19",
        date: "2025-09-12",
        games: "KK vs LL",
        pick: "KK",
        result: true,
        profit: "+130",
      },
      {
        id: "20",
        date: "2025-09-11",
        games: "MM vs NN",
        pick: "NN",
        result: true,
        profit: "+220",
      },
    ],
    tableFooterTitle: "Total Profit:",
  };
  const todayDate = new Date().toISOString().split("T")[0];
  const state = { tableMainData, todayDate, isAdmin };
  const handler = {};
  return { state, handler };
}
export default useAdminPageHook;
